version: '3.4'

services:
  autodealership:
    image: ${DOCKER_REGISTRY-}autodealership
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 80:80
    volumes:
     - .:c:/source
  db:
    image: octopusdeploy/mssql-server-windows-express
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
    env_file:
     - ./.env
    volumes:
     - ./db:c:/db

