# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: autodealership-config
  namespace: autodealership
data:
  ACCEPT_EULA: "Y"
  DB_HOST: db
  
---
