apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: autodealership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: ACCEPT_EULA
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: USER_PASSWORD
        - name: MSSQL_DATA_DIR
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MSSQL_DATA_DIR
        - name: MSSQL_LOG_DIR
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MSSQL_LOG_DIR
          
        volumeMounts:
        - name: mssql-base-volume
          mountPath: /var/opt/mssql
        - name: mssql-ldf-volume
          mountPath: /var/opt/mssql/ldf
        - name: mssql-mdf-volume
          mountPath: /var/opt/mssql/mdf
      volumes:
      - name: mssql-base-volume
        persistentVolumeClaim:
          claimName: mssql-base-volume
      - name: mssql-mdf-volume
        persistentVolumeClaim:
          claimName: mssql-mdf-volume
      - name: mssql-ldf-volume
        persistentVolumeClaim:
          claimName: mssql-ldf-volume		  
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: autodealership
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer