#mssql base volume claim: mssql-base-volume.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-base-volume
  namespace: autodealership
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#mssql data volume claim: mssql-mdf-volume.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-mdf-volume
  namespace: autodealership
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#mssql data volume claim for the logs

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-ldf-volume
  namespace: autodealership
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
#persistent volume claim for the autodealership app

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: autodealership-pvc
  namespace: autodealership
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi