apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-cloud-provider
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: NTFS
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
spec:
  storageClassName: google-cloud-provider
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
#comment
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: mssql-data-pvc
#   namespace: autodealership
#   # annotations:
#   #   volume.beta.kubernetes.io/storage-class: azure-disk
# spec:
#   storageClassName: google-cloud-provider
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi