name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Build and push AutoDealership Docker image to DockerHub repository"]
    types:
      - completed

env:
  PROJECT_ID: autodealership-398811
  PROJECT_NUMBER: 977500526177

  CLUSTER: autodealership-cluster
  CLUSTER_ZONE: europe-west4-a


  IMAGE: gorgilazarev3/autodealership:latest

jobs:
  build:
    runs-on: windows-2019  # Matches WINDOWS_LTSC in GKE
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    #
    # Authenticate to Google Cloud using workload identity federation
    #
    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v0'
      with:
        create_credentials_file: true
        token_format: access_token
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
        service_account: github-actions-workflow@${{ env.PROJECT_ID }}.iam.gserviceaccount.com


    - name: Connect to GKE
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.CLUSTER }}
        location: ${{ env.CLUSTER_ZONE }}

    #
    # Deploy to GKE
    #
    - name: Deploy to GKE
      run: |
        kubectl apply -f kubernetes/app-config-map.yaml
        kubectl apply -f kubernetes/app-secrets.yaml
        kubectl apply -f kubernetes/db-config-map.yaml
        kubectl apply -f kubernetes/db-secrets.yaml
        kubectl apply -f kubernetes/app-config-map.yaml
        kubectl apply -f kubernetes/app-secrets.yaml
        kubectl apply -f kubernetes/persistent-volume-claims.yaml
        kubectl apply -f kubernetes/db-deployment.yaml
        kubectl apply -f kubernetes/app-deployment.yaml
        kubectl apply -f kubernetes/ingress.yaml